"""
Keyword/indication definitions and matching rules for the InnoSer
prospection scraper. Migrated from the original Colab notebook.
"""

KEYWORDS = ['Acute kidney injury',
 'Addiction',
 "Alzheimer's disease",
 'Amyotrophic lateral sclerosis',
 'Angelman Syndrome',
 'Autism',
 'Autoimmune',
 'Breast Cancer',
 'Cardiology',
 'Cervical Cancer',
 'Charcot-Marie-Tooth disease',
 'Chronic kidney injury',
 'Colorectal Cancer',
 'Cystic fibrosis',
 'Depression',
 'Dermatology',
 'Diabetes',
 'Drug discovery and development',
 "Duchenne's Muscular Dystrophy",
 'Epilepsy',
 'Fibrosis',
 'Fragile-X',
 'Gastro-intestinal',
 'Glioblastoma',
 'Heart Failure',
 'Hematological Cancer',
 "Huntington's disease",
 'Hypertrophic',
 'IBD',
 'Immunology',
 'Infection',
 'Inflammation',
 'Ischemic',
 'Kabuki syndrome',
 'Leukemia',
 'Liquid tumor',
 'Liver disease',
 'Lung Cancer',
 'Lung fibrosis',
 'Mental disorder',
 'Metabolic',
 'Multiple Sclerosis',
 'Muscle disease',
 'NASH',
 'Nephrology',
 'Neurodegeneration',
 'Neurology',
 'Neuropathic pain',
 'Obesity',
 'Oncology',
 'Opthalmology',
 'Osteoarthritis',
 'Ovarian Cancer',
 'Pancreatic Cancer',
 "Parkinson's disease",
 'Peritoneal Cancer',
 'Personalized medicine',
 'Phelan-McDermid syndrome',
 'Polycystic kidney disease',
 'Psoriasis',
 'Rare disease',
 'Renal Cancer',
 'Respiratory disease',
 'Rheumatoid Arthritis',
 'Solid tumor',
 'Sepsis',
 'Spinal Cord Injury',
 'STXBP1 Encephalopathy',
 'Systemic Lupus Erythematosus',
 'Tuberous Sclerosis Complex (TSC)',
 'Vanishing White Matter',
 'Wound healing',
 'ADHD',
 'Anxiety',
 'Psychosis',
 'OCD',
 'Bipolar disorder',
 'Schizophrenia',
 'APOE4',
 'Neurodevelopmental disease',
 'Tau',
 'Amyloid',
 'TDP-43',
 'SOD1',
 'Frontotemporal dementia',
 'Acute Lung Inflammation',
 'Systemic inflammation',
 'Asthma',
 'Chronic obstructive pulmonary disease',
 'Pulmonary Fibrosis',
 'Peritonitis',
 'Skin inflammation',
 'Liver Inflammation',
 'Endometriosis',
 'Cytokine Storm',
 "Crohn's disease",
 'Ulcerative colitis',
 'GLP-1',
 'Type 1 diabetes',
 'Type 2 diabetes',
 'MASH',
 'Vascular disease',
 'Hypertension',
 'Thrombosis',
 'Myocardial Infarction',
 'Atherosclerosis',
 'Pulmonary Hypertension',
 'Cardiomyopathy',
 'Arrhythmia',
 '22q11.2 Deletion syndrome',
 'Rett Syndrome',
 'Dravet Syndrome',
 'CMT disease type 1A',
 'Liver Cancer',
 'Melanoma']

# lowercase keyword -> canonical (correctly capitalised) keyword
KEYWORD_CANONICAL = {k.lower(): k for k in KEYWORDS}

WHOLE_WORD_TERMS = ['adhd',
 'adpkd',
 'als',
 'apoe4',
 'cns',
 'copd',
 'glp-1',
 'ibd',
 'mash',
 'ms',
 'nafld',
 'nash',
 'ocd',
 'pdk',
 'sod1',
 'tdp-43',
 'tsc']

# alias (alternate name/spelling) -> canonical HubSpot keyword
ALIASES = {'22q11': '22q11.2 Deletion syndrome',
 'Amyotrophic lateral sclerosis': 'Muscle disease',
 'acute myocardial infarction': 'Myocardial Infarction',
 'acute renal failure': 'Acute kidney injury',
 'acute respiratory inflammation': 'Acute Lung Inflammation',
 'adpkd': 'Polycystic kidney disease',
 'adult-onset diabetes': 'Type 2 diabetes',
 'als': 'Amyotrophic lateral sclerosis',
 'alzheimer': "Alzheimer's disease",
 'amyloid beta': 'Amyloid',
 'amyloid plaques': 'Amyloid',
 'amyloid precursor': 'Amyloid',
 'angelman': 'Angelman Syndrome',
 'anxiety disorder': 'Anxiety',
 'apoe': 'APOE4',
 'apolipoprotein e': 'APOE4',
 'arrhythmic': 'Arrhythmia',
 'arterial disease': 'Vascular disease',
 'arterial hypertension': 'Hypertension',
 'arteriosclerosis': 'Atherosclerosis',
 'asthmatic': 'Asthma',
 'atopic dermatitis': 'Skin inflammation',
 'atrial fibrillation': 'Arrhythmia',
 'attention deficit': 'ADHD',
 'attention deficit hyperactivity': 'ADHD',
 'attention-deficit hyperactivity disorder': 'ADHD',
 'autoimmune disease': 'Autoimmune',
 'bipolar': 'Bipolar disorder',
 'blood cancer': 'Hematological Cancer',
 'blood vessel disease': 'Vascular disease',
 'brain health': 'Neurology',
 'bronchial asthma': 'Asthma',
 'cancer': 'Oncology',
 'carcinoma': 'Oncology',
 'cardiac arrhythmia': 'Arrhythmia',
 'cardiac disease': 'Cardiology',
 'cardiomyopathies': 'Cardiomyopathy',
 'cardiomyopathy': 'Cardiomyopathy',
 'cardiovascular': 'Cardiology',
 'central nervous system': 'Neurology',
 'charcot disease': 'Charcot-Marie-Tooth disease',
 'charcot marie tooth type 1': 'CMT disease type 1A',
 'chronic bronchitis': 'Chronic obstructive pulmonary disease',
 'chronic kidney disease': 'Chronic kidney injury',
 'chronic obstructive lung disease': 'Chronic obstructive pulmonary disease',
 'cmt type 1a': 'CMT disease type 1A',
 'cmt1a': 'CMT disease type 1A',
 'cns': 'Neurology',
 'colitis': 'Ulcerative colitis',
 'copd': 'Chronic obstructive pulmonary disease',
 'coronary artery disease': 'Atherosclerosis',
 'crohn': "Crohn's disease",
 "crohn's disease": "Crohn's disease",
 'crohns disease': "Crohn's disease",
 'cytokine release syndrome': 'Cytokine Storm',
 'cytokine storm syndrome': 'Cytokine Storm',
 'deep vein thrombosis': 'Thrombosis',
 'dermatitis': 'Skin inflammation',
 'developmental disorder': 'Neurodevelopmental disease',
 'diabetic': 'Diabetes',
 'digeorge syndrome': '22q11.2 Deletion syndrome',
 'digestive tract': 'Gastro-intestinal',
 'dmd': "Duchenne's Muscular Dystrophy",
 'dravet': 'Dravet Syndrome',
 'eczema': 'Skin inflammation',
 'emphysema': 'Chronic obstructive pulmonary disease',
 'endometrial': 'Endometriosis',
 'endometriotic': 'Endometriosis',
 'eye disease': 'Opthalmology',
 'eye health': 'Opthalmology',
 'fatty liver': 'Liver disease',
 'fragile x': 'Fragile-X',
 'frontotemporal': 'Frontotemporal dementia',
 'frontotemporal lobar degeneration': 'Frontotemporal dementia',
 'ftd': 'Frontotemporal dementia',
 'gastroenterology': 'Gastro-intestinal',
 'gastrointestinal': 'Gastro-intestinal',
 'gastrointestinal tract': 'Gastro-intestinal',
 'generalized anxiety': 'Anxiety',
 'glp1': 'GLP-1',
 'glucagon like peptide': 'GLP-1',
 'glucagon-like peptide': 'GLP-1',
 'heart attack': 'Myocardial Infarction',
 'hematologic malignancy': 'Hematological Cancer',
 'hepatic cancer': 'Liver Cancer',
 'hepatic fibrosis': 'Fibrosis',
 'hepatic inflammation': 'Liver Inflammation',
 'hepatocellular carcinoma': 'Liver Cancer',
 'high blood pressure': 'Hypertension',
 'huntingtons': "Huntington's disease",
 'hyperactivity disorder': 'ADHD',
 'hyperinflammation': 'Cytokine Storm',
 'ibd': 'IBD',
 'idiopathic pulmonary fibrosis': 'Pulmonary Fibrosis',
 'immunotherapy': 'Immunology',
 'infectious disease': 'Infection',
 'infectious diseases': 'Infection',
 'inflammatory bowel disease': 'IBD',
 'inflammatory disease': 'Inflammation',
 'insulin-dependent diabetes': 'Type 1 diabetes',
 'intestinal': 'Gastro-intestinal',
 'ischemia': 'Ischemic',
 'juvenile diabetes': 'Type 1 diabetes',
 'kidney cancer': 'Renal Cancer',
 'kidney disease': 'Nephrology',
 'kidney diseases': 'Nephrology',
 'liquid tumour': 'Liquid tumor',
 'liraglutide': 'GLP-1',
 'liver inflammation': 'Liver Inflammation',
 'lung inflammation': 'Acute Lung Inflammation',
 'lupus': 'Systemic Lupus Erythematosus',
 'major depressive disorder': 'Depression',
 'malignant melanoma': 'Melanoma',
 'manic depression': 'Bipolar disorder',
 'mash': 'MASH',
 'mecp2': 'Rett Syndrome',
 'melanocytic tumor': 'Melanoma',
 'melanoma': 'Melanoma',
 'mental illness': 'Mental disorder',
 'metabolic associated steatohepatitis': 'MASH',
 'metabolic disorder': 'Metabolic',
 'metabolic dysfunction associated steatohepatitis': 'MASH',
 'muscular dystrophy': 'Muscle disease',
 'nafld': 'Liver disease',
 'nash': 'NASH',
 'nervous system': 'Neurology',
 'neurodegenerative': 'Neurodegeneration',
 'neurodegenerative disease': 'Neurodegeneration',
 'neurodevelopmental disorder': 'Neurodevelopmental disease',
 'neurodevelopmental disorders': 'Neurodevelopmental disease',
 'neuropathic': 'Neuropathic pain',
 'neuroscience': 'Neurology',
 'non small cell lung cancer': 'Lung Cancer',
 'non-insulin-dependent diabetes': 'Type 2 diabetes',
 'obsessive compulsive': 'OCD',
 'obsessive-compulsive disorder': 'OCD',
 'ocular disease': 'Opthalmology',
 'ophthalmology': 'Opthalmology',
 'orphan disease': 'Rare disease',
 'ovarian carcinoma': 'Ovarian Cancer',
 'pancreatic carcinoma': 'Pancreatic Cancer',
 'panic disorder': 'Anxiety',
 'parkinson': "Parkinson's disease",
 'peripheral vascular': 'Vascular disease',
 'peritoneal inflammation': 'Peritonitis',
 'phelan mcdermid': 'Phelan-McDermid syndrome',
 'pkd': 'Polycystic kidney disease',
 'psoriatic arthritis': 'Psoriasis',
 'psychotic disorder': 'Psychosis',
 'pulmonary arterial hypertension': 'Pulmonary Hypertension',
 'pulmonary fibrosis': 'Pulmonary Fibrosis',
 'rare disorder': 'Rare disease',
 'renal disease': 'Chronic kidney injury',
 'respiratory disorder': 'Respiratory disease',
 'retinal disease': 'Opthalmology',
 'rett': 'Rett Syndrome',
 'schizophrenic': 'Schizophrenia',
 'scn1a': 'Dravet Syndrome',
 'semaglutide': 'GLP-1',
 'severe myoclonic epilepsy': 'Dravet Syndrome',
 'skin cancer': 'Melanoma',
 'skin disease': 'Dermatology',
 'skin inflammation': 'Skin inflammation',
 'sod1 mutation': 'SOD1',
 'solid tumour': 'Solid tumor',
 'spinal injury': 'Spinal Cord Injury',
 'steatohepatitis': 'NASH',
 'stxbp1': 'STXBP1 Encephalopathy',
 'superoxide dismutase': 'SOD1',
 'systemic inflammatory': 'Systemic inflammation',
 'tar dna-binding protein': 'TDP-43',
 'tau pathology': 'Tau',
 'tau protein': 'Tau',
 'tauopathy': 'Tau',
 'tdp 43': 'TDP-43',
 'tdp43': 'TDP-43',
 'thromboembolism': 'Thrombosis',
 'thrombus': 'Thrombosis',
 'tissue repair': 'Wound healing',
 'tsc': 'Tuberous Sclerosis Complex (TSC)',
 'tuberous sclerosis': 'Tuberous Sclerosis Complex (TSC)',
 'tumor': 'Oncology',
 'tumour': 'Oncology',
 'type i diabetes': 'Type 1 diabetes',
 'type ii diabetes': 'Type 2 diabetes',
 'ulcerative colitis': 'Ulcerative colitis',
 'velocardiofacial syndrome': '22q11.2 Deletion syndrome',
 'whole body inflammation': 'Systemic inflammation'}

# Parent-category auto-mapping. NOTE: some diseases (Alzheimer's, Parkinson's,
# ALS, MS, Huntington's, Spinal Cord Injury, Frontotemporal dementia) appear
# under BOTH "Neurology" and "Neurodegeneration" below. This is intentional:
# the reverse lookup (CHILD_TO_PARENT) resolves these to "Neurodegeneration"
# specifically (more precise), while broader CNS/psychiatric items (ADHD,
# Depression, Anxiety, Epilepsy, etc.) resolve to "Neurology". This was
# previously an unintentional side-effect of a duplicate dict key in the
# original notebook -- confirmed with Maud to be the desired behavior and
# is now made explicit here rather than left as an accident.
PARENT_CATEGORY_MAP = {'Cardiology': ['Heart Failure',
                'Hypertrophic',
                'Ischemic',
                'Vascular disease',
                'Hypertension',
                'Thrombosis',
                'Myocardial Infarction',
                'Atherosclerosis',
                'Pulmonary Hypertension',
                'Cardiomyopathy',
                'Arrhythmia'],
 'Immunology': ['Autoimmune',
                'Fibrosis',
                'IBD',
                'Infection',
                'Inflammation',
                'Osteoarthritis',
                'Psoriasis',
                'Rheumatoid Arthritis',
                'Sepsis',
                'Systemic Lupus Erythematosus',
                'Wound healing',
                'Acute Lung Inflammation',
                'Systemic inflammation',
                'Asthma',
                'Chronic obstructive pulmonary disease',
                'Pulmonary Fibrosis',
                'Peritonitis',
                'Skin inflammation',
                'Liver Inflammation',
                'Endometriosis',
                'Cytokine Storm',
                "Crohn's disease",
                'Ulcerative colitis'],
 'Metabolic': ['Aging',
               'Diabetes',
               'Gastro-intestinal',
               'Liver disease',
               'NASH',
               'Obesity',
               'Pancreatic fibrosis',
               'GLP-1',
               'Type 1 diabetes',
               'Type 2 diabetes',
               'MASH'],
 'Nephrology': ['Acute kidney injury',
                'Chronic kidney injury',
                'Polycystic kidney disease'],
 'Neurodegeneration': ["Alzheimer's disease",
                       "Parkinson's disease",
                       'Amyotrophic lateral sclerosis',
                       'Multiple Sclerosis',
                       "Huntington's disease",
                       'Spinal Cord Injury',
                       'Frontotemporal dementia'],
 'Neurology': ['Addiction',
               "Alzheimer's disease",
               'Amyotrophic lateral sclerosis',
               'Autism',
               'Depression',
               'Epilepsy',
               "Huntington's disease",
               'Mental disorder',
               'Multiple Sclerosis',
               'Neurodegeneration',
               'Neuropathic pain',
               "Parkinson's disease",
               'Spinal Cord Injury',
               'ADHD',
               'Anxiety',
               'Psychosis',
               'OCD',
               'Bipolar disorder',
               'Schizophrenia',
               'APOE4',
               'Neurodevelopmental disease',
               'Tau',
               'Amyloid',
               'TDP-43',
               'SOD1',
               'Frontotemporal dementia'],
 'Oncology': ['Breast Cancer',
              'Cervical Cancer',
              'Colorectal Cancer',
              'Glioblastoma',
              'Hematological Cancer',
              'Leukemia',
              'Liquid tumor',
              'Liver Cancer',
              'Lung Cancer',
              'Melanoma',
              'Ovarian Cancer',
              'Pancreatic Cancer',
              'Peritoneal Cancer',
              'Renal Cancer',
              'Solid tumor'],
 'Rare disease': ['Vanishing White Matter',
                  'STXBP1 Encephalopathy',
                  'Angelman Syndrome',
                  'Fragile-X',
                  '22q11.2 Deletion syndrome',
                  'Tuberous Sclerosis Complex (TSC)',
                  'Charcot-Marie-Tooth disease',
                  'CMT disease type 1A',
                  "Duchenne's Muscular Dystrophy",
                  'Phelan-McDermid syndrome',
                  'Kabuki syndrome',
                  'Rett Syndrome',
                  'Dravet Syndrome',
                  'Muscle disease',
                  'Cystic fibrosis',
                  'Neurodevelopmental disease',
                  'Autism',
                  'ADHD']}

CHILD_TO_PARENT = {}
for _parent, _children in PARENT_CATEGORY_MAP.items():
    for _child in _children:
        CHILD_TO_PARENT[_child] = _parent

EXCLUDED_URL_SEGMENTS = ['/careers',
 '/jobs',
 '/vacancies',
 '/join-us',
 '/join_us',
 '/team',
 '/our-team',
 '/people',
 '/about/team',
 '/about/leadership',
 '/about/management',
 '/about/board',
 '/about/founders',
 '/about/advisors',
 '/about/history',
 '/about/mission',
 '/about/our-mission',
 '/about/values',
 '/about/culture',
 '/about/story',
 '/about#',
 '/about-us',
 '/leadership',
 '/founders',
 '/advisors',
 '/board',
 '/management',
 '/our-mission',
 '/mission',
 '/values',
 '/history',
 '/culture',
 '/story',
 '/investors',
 '/investor-relations',
 '/investor_relations',
 '/financials',
 '/sec-filings',
 '/stock',
 '/shareholder',
 '/annual-report',
 '/quarterly',
 '/media-release',
 '/media-releases',
 '/press',
 '/media',
 '/blog',
 '/events',
 '/announcements',
 '/updates',
 '/press-release',
 '/press-releases',
 '/legal',
 '/privacy',
 '/cookie',
 '/terms',
 '/contact',
 '/support',
 '/faq',
 '/sitemap',
 '/accessibility',
 '/disclaimer',
 '/copyright',
 '/partners',
 '/partnership',
 '/partnering',
 '/grants',
 '/funding',
 '/csr',
 '/sustainability',
 '/patient',
 '/patients',
 '/caregivers',
 '/testimonials',
 '/gallery',
 '/awards',
 '/our-innovation',
 '/dam/']

SAFETY_PHRASES = ['contraindicated',
 'contraindication',
 'important safety information',
 'for healthcare professionals only',
 'prescribing information',
 'summary of product characteristics',
 'smpc',
 'patient information leaflet',
 'legal notice',
 'disclaimer',
 'do not use',
 'not to be used',
 'should not be used',
 'not recommended',
 'hypersensitivity',
 'adverse reactions']

COMPANY_INTENT_PHRASES = ['we are developing',
 'we develop',
 'in development for',
 'developing for',
 'designed to treat',
 'developed to treat',
 'being evaluated in',
 'being evaluated for',
 'our therapy',
 'our drug',
 'our compound',
 'our candidate',
 'our program',
 'our pipeline',
 'our lead',
 'our treatment',
 'clinical program',
 'lead program',
 'lead candidate',
 'phase 1',
 'phase 2',
 'phase 3',
 'phase i',
 'phase ii',
 'phase iii',
 'clinical trial',
 'clinical study',
 'clinical development',
 'ind ',
 'ind-enabling',
 'investigational new drug',
 'focused on',
 'dedicated to',
 'addressing',
 'pioneering',
 'working on',
 'solutions for',
 'our research focuses on',
 'our therapy aims to',
 'innovating in',
 'approved for',
 'indicated for',
 'fda approved',
 'ema approved',
 'fda-approved',
 'ema-approved',
 'orphan drug designation',
 'breakthrough therapy',
 'fast track designation']

REJECTION_PHRASES = ['not pursuing',
 'previously studied',
 'divested',
 'discontinued',
 'no longer active in',
 'ended development for',
 'historical focus',
 'legacy projects',
 'years of experience',
 'years experience',
 'experience across',
 'experience spanning',
 'expertise across',
 'background in',
 'background spanning',
 'prior to joining',
 'before joining',
 'previously served',
 'previously worked',
 'held positions',
 'held roles',
 'his career',
 'her career',
 'their career',
 'throughout his',
 'throughout her',
 'he has worked',
 'she has worked',
 'he brings',
 'she brings',
 'trained in',
 'trained at',
 'across the fields of',
 'across the areas of',
 'including oncology',
 'such as oncology']

FOCUS_SECTION_LABELS = ['pipeline',
 'portfolio',
 'our science',
 'research areas',
 'therapeutic areas',
 'development programs',
 'our focus',
 'our programs',
 'our platform',
 'indications',
 'disease areas',
 'clinical stage',
 'preclinical',
 'phase 1',
 'phase 2',
 'phase 3',
 'phase i',
 'phase ii',
 'phase iii',
 'approved',
 'marketed',
 'in development',
 'our medicines',
 'our treatments']

FOCUS_URL_SEGMENTS = [
    'investment',
    'investments',
    'portfolio',
    'strategy',
    'focus',
    'thesis',
    'fund',
    'team',
    'about']

SKIP_SECTION_LABELS = ['our team',
 'management',
 'board of directors',
 'scientific advisory board',
 'leadership',
 'founders',
 'our people',
 'careers',
 'job openings',
 'join us',
 'vacancies',
 'partnerships',
 'collaborators',
 'investors',
 'co-development',
 'alliance',
 'funding',
 'grants',
 'partnering opportunities',
 'news',
 'press release',
 'announcement',
 'media',
 'updates']

BIO_PHRASES = ['brings over',
 'brings more than',
 'years of experience',
 'prior to joining',
 'before joining',
 'previously served',
 'served as ceo',
 'served as cso',
 'served as cmo',
 'served as cbo',
 'served as cfo',
 'held roles at',
 'he held',
 'she held',
 'his career',
 'her career',
 'earned his',
 'earned her',
 'received his',
 'received her',
 'ph.d. from',
 'm.d. from',
 'm.b.a. from',
 'postdoctoral',
 'board certified',
 'undergraduate degree',
 'his ph.d',
 'her ph.d',
 'vice president at',
 'vice president of',
 'career focused on',
 'extensive experience in',
 'experience spanning',
 'prior to ventus',
 'prior to his',
 'prior to her',
 'leading the team that',
 'he was cmo',
 'he was cso',
 'he was ceo',
 'she was cmo',
 'she was cso',
 'she was cee',
 'qualified in medicine',
 'trained at',
 'postdoctoral training',
 'faculty member at',
 'director of research at']

# Signals that indicate a company is a service/tools/academic org, not a
# drug developer. Only used as a fallback when keyword rules are ambiguous.
EXCLUSION_SIGNALS = {'Academic / Non-profit': ['university',
                           'research institute',
                           'patient advocacy',
                           'patient foundation',
                           'non-profit organization',
                           'nonprofit organization',
                           'not-for-profit',
                           'charitable organization',
                           'academic medical center',
                           'research hospital'],
 'CDMO': ['contract development and manufacturing organization',
          'contract manufacturing organization',
          'cdmo services',
          'gmp manufacturing services',
          'manufacturing services for',
          'we manufacture for',
          'fill and finish services',
          'drug substance manufacturing services',
          'drug product manufacturing services',
          'manufacturing partner'],
 'CRO': ['contract research organization',
         'clinical research organization',
         'cro services',
         'we provide clinical trial',
         'clinical trial management services',
         'regulatory affairs services',
         'pharmacokinetic services',
         'we support pharma',
         'we support biotech',
         'outsourced research'],
 'Diagnostics / Tools': ['in vitro diagnostic',
                         'laboratory instruments',
                         'research tools and reagents',
                         'assay kits',
                         'sequencing services',
                         'diagnostic testing services',
                         'laboratory information management',
                         'lab equipment']}

MIN_EXCLUSION_SIGNALS = 2

PIPELINE_IMAGE_KEYWORDS = [
    "pipeline", "programs", "platform", "portfolio",
    "development", "indication", "therapeutic",
]

PRIORITY_WORDS = [
    "pipeline", "portfolio", "product", "products", "technology",
    "science", "research", "therapeutic", "indication", "disease",
    "clinical", "platform",
]

EXCLUSION_CHECK_PROMPT = """You are screening a database of life sciences companies.

Your job is simple: decide if the company described on this homepage is a
drug-developing company (Biotech or Pharma) OR a service/tools/academic company
(CRO, CDMO, diagnostics, university, foundation, etc.).

Reply with EXACTLY one word:
- "yes" if they develop their own drugs, therapies, or treatments
- "no" if they primarily provide services, tools, or research to other companies

Homepage text:
{homepage_text}"""
